# Generated by Django 2.2 on 2020-02-09 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0003_event_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='due_date',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_date',
            new_name='start',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_description',
        ),
    ]
